# بيان مصرف ليبيا المركزي
عن الإيراد والإنفاق من 2023/01/01 حتى 2023/12/31

## الإيراد:
(الأرقام بالدينار الليبي)

| البيان | 2021 | 2022 | 2023 |
|--------|------|------|------|
| إيرادات مبيعات نفطية | 103.4 مليار | 105.5 مليار | 99.1 مليار |
| إيرادات إتاوات نفطية | 0 | 13.6 مليار | 12.3 مليار |
| إيراد إتاوات نفطية عن سنوات سابقة | 0 | 11.4 مليار | 10.3 مليار |
| إيرادات الضرائب | 799 مليون | 1.4 مليار | 2.4 مليار |
| إيرادات الجمارك | 311 مليون | 211 مليون | 333 مليون |
| إيرادات الاتصالات | 198 مليون | 529 مليون | 506 مليون |
| إيرادات بيع المحروقات بالسوق المحلي | 450 مليون | 265 مليون | 180 مليون |
| إيرادات أخرى* | 494 مليون | 1.5 مليار | 792 مليون |
| الإجمالي | 105.7 مليار | 134.4 مليار | 125.9 مليار |

*إيرادات أخرى تمثل إيرادات واردة من مراقبات الخدمات المالية بالمدن الليبية نظير خدمات عامة، وتمثّل: (مسترجعات، رسوم جوازات، وتمليك سيارات، وغرامات، وغيرها من الرسوم).

## الإنفاق:
(الأرقام بالدينار الليبي)

| البيان | 2021 | 2022 | 2023 |
|--------|------|------|------|
| الباب الأول (المرتبات) | 33.1 مليار | 47.1 مليار | 60 مليار* |
| الباب الثاني (النفقات التسييرية) | 8 مليار | 9 مليار | 9 مليار |
| الباب الثالث (التنمية) | 17.4 مليار | 17.5 مليار | 12 مليار |
| الباب الرابع (الدعم) | 20.8 مليار | 20 مليار** | 20 مليار** |
| الباب الخامس (الطوارئ) | 6.5 مليار | 0 | 0 |
| إجمالي الإنفاق على الأبواب | 85.8 مليار | 93.6 مليار دينار | 101 مليار |
| ميزانية استثنائية للمؤسسة الوطنية للنفط | 0 | 34.3 مليار | 17.5 مليار |
| ميزانية استثنائية للشركة العامة للكهرباء | 0 | 0 | 7.2 مليار |
| إجمالي الإنفاق العام | 85.8 مليار | 127.9 مليار | 125.7 مليار |

* إضافة لمبالغ أخرى تقدر بحوالي 5 مليار دينار تشمل: 4 مليار دينار للمؤسسة الوطنية للنفط، ومليار لجهات أخرى.

**لا يشمل باب الدعم دعم المحروقات في عامي 2022-2023 حيث تقوم المؤسسة الوطنية للنفط بخصم قيمتها عن طريق المبادلة.

| القطاعات والجهات التابعة لها | الباب الأول | الباب الثاني | الباب الثالث | الباب الرابع | الباب الخامس | إجمالي الإنفاق للجهة |
|----------------------------------|----------------|----------------|----------------|----------------|----------------|------------------------|
| 01- مجلس النواب والجهات التابعة له | 1,044,980,262.304 | 360,934,072.000 | 265,227,088.000 | 00.000 | 00.000 | 1,671,141,422.304 |
| 02- المجلس الأعلى للدولة | 45,276,774.214 | 34,999,999.000 | 00.000 | 00.000 | 00.000 | 80,276,773.214 |
| 03- المجلس الرئاسي والجهات التابعة له | 639,890,010.232 | 131,000,000.000 | 00.000 | 00.000 | 00.000 | 770,890,010.232 |
| 04- مجلس الوزراء والجهات التابعة له | 1,463,514,006.882 | 1,561,046,013.000 | 00.000 | 00.000 | 00.000 | 3,024,560,019.882 |
| 05- وزارة المالية والجهات التابعة لها | 27,354,192,130.556 | 620,182,435.000 | 10,032,548,920.000 | 329,768,812.000 | 00.000 | 38,336,692,297.556 |
| 06- وزارة الدفاع والجهات التابعة لها | 3,992,044,651.192 | 347,649,998.000 | 00.000 | 00.000 | 00.000 | 4,339,694,649.192 |
| 07- وزارة الداخلية والجهات التابعة لها | 4,473,493,618.963 | 685,580,673.000 | 112,800,000.000 | 00.000 | 00.000 | 5,271,874,291.963 |
| 08- وزارة العدل والجهات التابعة لها | 1,392,708,780.949 | 582,650,000.000 | 18,000,000.000 | 00.000 | 00.000 | 1,993,358,780.949 |
| 09- وزارة الخارجية والتعاون الدولي والجهات التابعة لها | 1,614,627,052.760 | 1,085,651,101.040 | 725,623,269.000 | 00.000 | 00.000 | 3,425,901,422.800 |
| 10- وزارة النفط والغاز والجهات التابعة لها | 15,363,465.811 | 6,000,000.000 | 00.000 | 00.000 | 00.000 | 21,363,465.811 |
| 11- وزارة الصحة والجهات التابعة لها | 2,775,624,173.281 | 1,472,458,458.000 | 00.000 | 4,149,533,000.000 | 00.000 | 8,397,615,631.281 |
| 12- وزارة التربية والتعليم والجهات التابعة لها | 322,726,095.943 | 146,416,666.000 | 422,296,823.000 | 00.000 | 00.000 | 891,439,584.943 |
| 13- وزارة التعليم العالي والبحث العلمي والجهات التابعة لها | 2,200,834,588.968 | 241,716,649.500 | 272,000,000.000 | 00.000 | 00.000 | 2,714,551,238.468 |
| 14- وزارة التعليم التقني والفني والجهات التابعة لها | 449,652,620.610 | 27,500,000.000 | 00.000 | 00.000 | 00.000 | 477,152,620.610 |
| 15- وزارة الاقتصاد والتجارة والجهات التابعة لها | 88,339,066.975 | 70,626,140.000 | 00.000 | 00.000 | 00.000 | 158,965,206.975 |
| 16- وزارة الصناعة والمعادن والجهات التابعة لها | 31,439,199.570 | 18,753,706.000 | 00.000 | 00.000 | 00.000 | 50,192,905.570 |
| 17- وزارة المواصلات والجهات التابعة لها | 221,965,420.309 | 103,211,086.501 | 00.000 | 00.000 | 00.000 | 325,176,506.810 |
| 18- وزارة الشؤون الاجتماعية والجهات التابعة لها | 8,529,494,424.261 | 153,369,838.334 | 00.000 | 8,389,677,554.000 | 00.000 | 17,072,541,816.595 |
| 19- وزارة التخطيط والجهات التابعة لها | 19,335,055.672 | 10,799,999.000 | 00.000 | 00.000 | 00.000 | 30,135,054.672 |
| 20- وزارة الحكم المحلي والجهات التابعة لها | 1,960,808,242.213 | 500,100,618.420 | 00.000 | 750,000,000.000 | 00.000 | 3,210,908,860.633 |
| 21- وزارة الزراعة والثروة الحيوانية والجهات التابعة لها | 372,330,358.609 | 58,674,997.667 | 00.000 | 00.000 | 00.000 | 431,005,356.276 |
| 22- وزارة الثروة البحرية والجهات التابعة لها | 137,800,228.957 | 12,800,000.000 | 00.000 | 00.000 | 00.000 | 150,600,228.957 |
| 23- وزارة العمل والتأهيل والجهات التابعة لها | 33,631,099.759 | 26,356,353.000 | 00.000 | 00.000 | 00.000 | 59,987,452.759 |
| 24- وزارة الإسكان والتعمير والجهات التابعة لها | 70,810,648.600 | 40,549,836.000 | 135,000,000.000 | 00.000 | 00.000 | 246,360,484.600 |
| 25- وزارة السياحة والصناعات التقليدية والجهات التابعة لها | 262,097,158.621 | 9,750,000.000 | 00.000 | 00.000 | 00.000 | 271,847,158.621 |
| 26- وزارة الثقافة والتنمية المعرفية والجهات التابعة لها | 128,578,166.775 | 29,159,998.000 | 15,459,100.000 | 00.000 | 00.000 | 173,197,264.775 |
| 27- وزارة الرياضة والجهات التابعة لها | 142,750,812.424 | 83,166,667.000 | 00.000 | 385,000,000.000 | 00.000 | 610,917,479.424 |
| 28- وزارة الشباب والجهات التابعة لها | 11,667,709.351 | 46,200,000.000 | 00.000 | 175,000,000.000 | 00.000 | 232,867,709.351 |
| 29- وزارة الخدمة المدنية والجهات التابعة لها | 11,073,512.482 | 7,499,999.000 | 00.000 | 00.000 | 00.000 | 18,573,511.482 |
| 30- وزارة الموارد المائية والجهات التابعة لها | 24,122,240.697 | 89,773,762.000 | 00.000 | 580,000,001.000 | 00.000 | 693,896,003.697 |
| 31- وزارة البيئة والجهات التابعة لها | 58,975,902.593 | 6,000,000.000 | 00.000 | 00.000 | 00.000 | 64,975,902.593 |
| 32- هيئة رعاية أسر الشهداء والمفقودين | 13,320,448.782 | 131,759,029.000 | 00.000 | 856,018,057.000 | 00.000 | 1,001,097,534.782 |
| 33- الهيئة العامة للأوقاف والشؤون الإسلامية والجهات التابعة لها | 60,800,240.539 | 167,510,500.000 | 00.000 | 00.000 | 00.000 | 228,310,740.539 |
| 34- الهيئة العامة للاتصالات والجهات التابعة لها | 34,202,918.218 | 5,999,999.000 | 00.000 | 00.000 | 00.000 | 40,202,917.218 |
| 35- الشركة العامة للكهرباء | 00.000 | 114,666,667.000 | 00.000 | 4,385,000,000.000 | 00.000 | 4,499,666,667.000 |
| 36- المؤسسة الوطنية للنفط (ميزانية استثنائية) | 3,933,507,000.000 | 1,237,500,000.000 | 12,371,750,387.000 | 00.000 | 00.000 | 17,542,757,387.000 |
| 37- الشركة العامة للكهرباء (ميزانية استثنائية) | 00.000 | 00.000 | 7,195,666,525.000 | 00.000 | 00.000 | 7,195,666,525.000 |
| الإجمالي | 63,931,978,088.072 | 10,228,015,260.462 | 31,566,372,112.000 | 19,999,997,424.000 | 00.000 | 125,726,362,884.528 |



# وزارة المالية والجهات التابعة لها:

المبالغ المحالة إلى مراقبات الخدمات المالية بالمدن (الباب الأول: المرتبات)
(الأرقام بالدينار الليبي)
[
  {
    "الإجمالي": 13463968.503,
    "الجهة": "مراقبة الخدمات المالية - اجخرة",
    "ت": 1
  },
  {
    "الإجمالي": 385615539.087,
    "الجهة": "مراقبة الخدمات المالية - اجدابيا",
    "ت": 2
  },
  {
    "الإجمالي": 82636903.485,
    "الجهة": "مراقبة الخدمات المالية - الأبرق",
    "ت": 3
  },
  {
    "الإجمالي": 409682722.185,
    "الجهة": "مراقبة الخدمات المالية - الأبيار",
    "ت": 4
  },
  {
    "الإجمالي": 193187327.852,
    "الجهة": "مكتب الخدمات المالية - الأصابعة",
    "ت": 5
  },
  {
    "الإجمالي": 62508581.173,
    "الجهة": "مراقبة الخدمات المالية - البريقة",
    "ت": 6
  },
  {
    "الإجمالي": 782500.842,
    "الجهة": "مكتب الخدمات المالية - البوانيس",
    "ت": 7
  },
  {
    "الإجمالي": 1122319166.024,
    "الجهة": "مراقبة الخدمات المالية - البيضاء",
    "ت": 8
  },
  {
    "الإجمالي": 15567009.684,
    "الجهة": "مراقبة الخدمات المالية - الجغبوب",
    "ت": 9
  },
  {
    "الإجمالي": 1090331434.815,
    "الجهة": "مراقبة الخدمات المالية - الجفارة",
    "ت": 10
  },
  {
    "الإجمالي": 228544735.892,
    "الجهة": "مراقبة الخدمات المالية - الجفرة",
    "ت": 11
  },
  {
    "الإجمالي": 342527651.226,
    "الجهة": "مراقبة الخدمات المالية - الجميل",
    "ت": 12
  },
  {
    "الإجمالي": 39847290.225,
    "الجهة": "مراقبة الخدمات المالية - الحرابة",
    "ت": 13
  },
  {
    "الإجمالي": 592694242.537,
    "الجهة": "مراقبة الخدمات المالية - الخمس",
    "ت": 14
  },
  {
    "الإجمالي": 39037669.047,
    "الجهة": "مراقبة الخدمات المالية - الرجبان",
    "ت": 15
  },
  {
    "الإجمالي": 48371212.695,
    "الجهة": "مراقبة الخدمات المالية - الرحيبات",
    "ت": 16
  },
  {
    "الإجمالي": 28849611.065,
    "الجهة": "مراقبة الخدمات المالية - الرياينة",
    "ت": 17
  },
  {
    "الإجمالي": 831976679.197,
    "الجهة": "مراقبة الخدمات المالية - الزاوية",
    "ت": 18
  },
  {
    "الإجمالي": 55155342.265,
    "الجهة": "مراقبة الخدمات المالية - الزاوية الجنوب",
    "ت": 19
  },
  {
    "الإجمالي": 308665253.339,
    "الجهة": "مراقبة الخدمات المالية - الزاوية الغرب",
    "ت": 20
  },
  {
    "الإجمالي": 89831574.478,
    "الجهة": "مراقبة الخدمات المالية - الزنتان",
    "ت": 21
  },
  {
    "الإجمالي": 51143898.607,
    "الجهة": "مكتب الخدمات المالية - الزويتينة",
    "ت": 22
  },
  {
    "الإجمالي": 47537382.609,
    "الجهة": "مراقبة الخدمات المالية - السائح",
    "ت": 23
  },
  {
    "الإجمالي": 64852684.490,
    "الجهة": "مكتب الخدمات المالية - السبيعة",
    "ت": 24
  },
  {
    "الإجمالي": 62089332.364,
    "الجهة": "مراقبة الخدمات المالية - السدرة",
    "ت": 25
  },
  {
    "الإجمالي": 4192539.671,
    "الجهة": "مكتب الخدمات المالية - الشعبة",
    "ت": 26
  },
  {
    "الإجمالي": 106361985.377,
    "الجهة": "مراقبة الخدمات المالية - الشقيقة",
    "ت": 27
  },
  {
    "الإجمالي": 17748892.428,
    "الجهة": "مراقبة الخدمات المالية - الشويرف",
    "ت": 28
  },
  {
    "الإجمالي": 534207565.060,
    "الجهة": "مراقبة الخدمات المالية - العجيلات",
    "ت": 29
  },
  {
    "الإجمالي": 49216518.866,
    "الجهة": "مراقبة الخدمات المالية - العربان",
    "ت": 30
  },
  {
    "الإجمالي": 193617408.404,
    "الجهة": "مراقبة الخدمات المالية - القبة",
    "ت": 31
  },
  {
    "الإجمالي": 227008565.317,
    "الجهة": "مراقبة الخدمات المالية - القره بوللي",
    "ت": 32
  },
  {
    "الإجمالي": 46414292.825,
    "الجهة": "مكتب الخدمات المالية - القلعة",
    "ت": 33
  },
  {
    "الإجمالي": 34232630.315,
    "الجهة": "مراقبة الخدمات المالية - القيقب",
    "ت": 34
  },
  {
    "الإجمالي": 190463538.919,
    "الجهة": "مراقبة الخدمات المالية - الكفرة",
    "ت": 35
  },
  {
    "الإجمالي": 445948362.440,
    "الجهة": "مراقبة الخدمات المالية - المرج",
    "ت": 36
  },
  {
    "الإجمالي": 37988495.585,
    "الجهة": "مكتب الخدمات المالية - المليطانية",
    "ت": 37
  },
  {
    "الإجمالي": 62080010.517,
    "الجهة": "مراقبة الخدمات المالية - امساعد",
    "ت": 38
  },
  {
    "الإجمالي": 13392536.426,
    "الجهة": "مراقبة الخدمات المالية - انتلات البيضان",
    "ت": 39
  },
  {
    "الإجمالي": 39657480.341,
    "الجهة": "مراقبة الخدمات المالية - أم الرزم",
    "ت": 40
  },
{
    "الإجمالي": 32620913.410,
    "الجهة": "مراقبة الخدمات المالية - أوجلة",
    "ت": 41
  },
{
    "الإجمالي": 142661421.454,
    "الجهة": "مراقبة الخدمات المالية - باطن الجبل",
    "ت": 42
  },
{
    "الإجمالي": 25585214.184,
    "الجهة": "مراقبة الخدمات المالية - بلدية الحوامد",
    "ت": 43
  },
{
    "الإجمالي": 38262389.126,
    "الجهة": "مراقبة الخدمات المالية - بلدية الشرقية",
    "ت": 44
  },
{
    "الإجمالي": 18637383.260,
    "الجهة": "مراقبة الخدمات المالية - بنت بية",
    "ت": 45
  },
{
    "الإجمالي": 4127610497.316,
    "الجهة": "مراقبة الخدمات المالية - بنغازي",
    "ت": 46
  },
{
    "الإجمالي": 404598385.576,
    "الجهة": "مراقبة الخدمات المالية - بني وليد",
    "ت": 47
  },
{
    "الإجمالي": 22871060.875,
    "الجهة": "مكتب الخدمات المالية - بنينا",
    "ت": 48
  },
{
    "الإجمالي": 98384838.782,
    "الجهة": "مراقبة الخدمات المالية - بئر الأشهب",
    "ت": 49
  },
{
    "الإجمالي": 22493262.794,
    "الجهة": "مراقبة الخدمات المالية - تازربو",
    "ت": 50
  },
{
    "الإجمالي": 46123446.687,
    "الجهة": "مراقبة الخدمات المالية - تاورغاء",
    "ت": 51
  },
{
    "الإجمالي": 11542581.392,
    "الجهة": "مكتب الخدمات المالية - تراغن",
    "ت": 52
  },
{
    "الإجمالي": 540380707.767,
    "الجهة": "مراقبة الخدمات المالية - ترهونة",
    "ت": 53
  },
{
    "الإجمالي": 180712864.990,
    "الجهة": "مراقبة الخدمات المالية - توكرة",
    "ت": 54
  },
{
    "الإجمالي": 79508701.159,
    "الجهة": "مراقبة الخدمات المالية - جادو",
    "ت": 55
  },
{
    "الإجمالي": 100267194.548,
    "الجهة": "مراقبة الخدمات المالية - جالو",
    "ت": 56
  },
{
    "الإجمالي": 109009716.271,
    "الجهة": "مراقبة الخدمات المالية - جردس العبيد",
    "ت": 57
  },
{
    "الإجمالي": 416936061.777,
    "الجهة": "مراقبة الخدمات المالية - جنزور",
    "ت": 58
  },
{
    "الإجمالي": 609147560.816,
    "الجهة": "مراقبة الخدمات المالية - درنة",
    "ت": 59
  },
{
    "الإجمالي": 136516844.741,
    "الجهة": "مراقبة الخدمات المالية - رقدالين",
    "ت": 60
  },
{
    "الإجمالي": 83549831.255,
    "الجهة": "مراقبة الخدمات المالية - زلطن",
    "ت": 61
  },
{
    "الإجمالي": 485661988.809,
    "الجهة": "مكتب الخدمات المالية - زليتن",
    "ت": 62
  },
{
    "الإجمالي": 136177583.028,
    "الجهة": "مراقبة الخدمات المالية - زوارة",
    "ت": 63
  },
{
    "الإجمالي": 209126759.393,
    "الجهة": "مراقبة الخدمات المالية - ساحل الجبل",
    "ت": 64
  },
{
    "الإجمالي": 366467459.654,
    "الجهة": "مراقبة الخدمات المالية - سبها",
    "ت": 65
  },
{
    "الإجمالي": 318962499.070,
    "الجهة": "مراقبة الخدمات المالية - سرت",
    "ت": 66
  },
{
    "الإجمالي": 91069591.740,
    "الجهة": "مراقبة الخدمات المالية - سلوق",
    "ت": 67
  },
{
    "الإجمالي": 362321603.241,
    "الجهة": "مراقبة الخدمات المالية - شحات",
    "ت": 68
  },
{
    "الإجمالي": 414814333.907,
    "الجهة": "مراقبة الخدمات المالية - صبراتة",
    "ت": 69
  },
{
    "الإجمالي": 303814680.446,
    "الجهة": "مراقبة الخدمات المالية - صرمان",
    "ت": 70
  },
{
    "الإجمالي": 147776370.746,
    "الجهة": "مراقبة الخدمات المالية - مزدة",
    "ت": 85
  },
  {
    "الإجمالي": 536500995.213,
    "الجهة": "مراقبة الخدمات المالية - طبرق",
    "ت": 71
  },
  {
    "الإجمالي": 130885462.320,
    "الجهة": "مكتب الخدمات المالية - مسلاتة",
    "ت": 86
  },
  {
    "الإجمالي": 2371875258.565,
    "الجهة": "مراقبة الخدمات المالية - طرابلس",
    "ت": 72
  },
  {
    "الإجمالي": 645673595.195,
    "الجهة": "مراقبة الخدمات المالية - مصراتة",
    "ت": 87
  },
  {
    "الإجمالي": 46006573.969,
    "الجهة": "مكتب الخدمات المالية - ظاهر الجبل",
    "ت": 73
  },
  {
    "الإجمالي": 5337966.718,
    "الجهة": "مكتب الخدمات المالية - منطقة زبيانة الإدارية",
    "ت": 88
  },
  {
    "الإجمالي": 74264790.255,
    "الجهة": "مراقبة الخدمات المالية - غات",
    "ت": 74
  },
  {
    "الإجمالي": 185967399.852,
    "الجهة": "مراقبة الخدمات المالية - نالوت",
    "ت": 89
  },
  {
    "الإجمالي": 61205429.362,
    "الجهة": "مراقبة الخدمات المالية - غدامس",
    "ت": 75
  },
  {
    "الإجمالي": 301935374.907,
    "الجهة": "مراقبة الخدمات المالية - وادي الآجال",
    "ت": 90
  },
  {
    "الإجمالي": 728835812.155,
    "الجهة": "مراقبة الخدمات المالية - غريان",
    "ت": 76
  },
  {
    "الإجمالي": 523675964.184,
    "الجهة": "مراقبة الخدمات المالية - وادي الشاطئ",
    "ت": 91
  },
  {
    "الإجمالي": 104751694.479,
    "الجهة": "مكتب الخدمات المالية - قصر الأخيار",
    "ت": 77
  },
  {
    "الإجمالي": 1205658.247,
    "الجهة": "مكتب الخدمات المالية - وازن",
    "ت": 92
  },
  {
    "الإجمالي": 8884490.026,
    "الجهة": "مكتب الخدمات المالية - قصر الجدي",
    "ت": 78
  },
  {
    "الإجمالي": 804012.967,
    "الجهة": "مراقبة الخدمات المالية - واو الناموس",
    "ت": 93
  },
  {
    "الإجمالي": 339336537.548,
    "الجهة": "مراقبة الخدمات المالية - قصر بن غشير",
    "ت": 79
  },
  {
    "الإجمالي": 35235377.288,
    "الجهة": "مكتب الخدمات المالية - وردامة",
    "ت": 94
  },
  {
    "الإجمالي": 70688173.249,
    "الجهة": "مراقبة الخدمات المالية - قمينس",
    "ت": 80
  },
  {
    "الإجمالي": 82774071.232,
    "الجهة": "مكتب الخدمات المالية - يفرن",
    "ت": 95
  },
  {
    "الإجمالي": 55637970.704,
    "الجهة": "مراقبة الخدمات المالية - كاباو",
    "ت": 81
  },
  {
    "الإجمالي": 254567.963,
    "الجهة": "مراقبة الخدمات المالية - بلدية هراوة",
    "ت": 96
  },
  {
    "الإجمالي": 51546171.281,
    "الجهة": "مراقبة الخدمات المالية - ككلة",
    "ت": 82
  },
  {
    "الإجمالي": 313902.765,
    "الجهة": "مراقبة الخدمات المالية - بلدية العوينات",
    "ت": 97
  },
  {
    "الإجمالي": 29403983.810,
    "الجهة": "مراقبة الخدمات المالية - مرادة",
    "ت": 83
  },
  {
    "الإجمالي": 2842083.649,
    "الجهة": "مراقبة الخدمات المالية - بلدية المشاشية",
    "ت": 98
  },
  {
    "الإجمالي": 234886945.420,
    "الجهة": "مراقبة الخدمات المالية - مرزق",
    "ت": 84
  },
{
    "الإجمالي": 24,924,094,547.714,
    "الجهة": "الإجمالي",
    "ت": null 
  }
]


## استخدامات النقد الأجنبي:
(الأرقام بالمليون دولار أمريكي)
**استخدامات والتزامات الدولة عن طريق مصرف ليبيا المركزي (مليون دولار أمريكي)**

| البيان                                                                  | 2023  | 2022  | 2021  |
| :--------------------------------------------------------------------- | ----: | ----: | ----: |
| مرتبات العاملين بالخارج                                                    |   339 |   247 |   155 |
| منح الطلبة الدارسين بالخارج                                                |   102 |   142 |   157 |
| العلاج بالخارج                                                         |   108 |   163 |    52 |
| دعم المصروفات                                                         |     0 |     0 | 2,197 |
| المؤسسة الوطنية للنفط                                                     | 2,548 | 2,365 |   803 |
| حوالات لصالح جهات أخرى                                                 |   917 |   512 |   948 |
| جهاز الإمداد الطبي                                                          |   377 |   269 |   331 |
| الشركة العامة للكهرباء                                                   |   741 |   465 |   663 |
| التعليم والتعليم العالي                                                   |    26 |    88 |    57 |
| اعتمادات لصالح جهات أخرى                                               |   280 |   166 |   249 |
| التزامات قائمة على جهات عامة                                                  | 8,894 | 7,926 | 3,613 |
| **المجموع الفرعي: استخدامات والتزامات الدولة**                            |**14,332**|**12,343**|**9,225**|

**استخدامات المصارف التجارية (مليون دولار أمريكي)**

| البيان                                                                     | 2023  | 2022  | 2021  |
| :------------------------------------------------------------------------ | ----: | ----: | ----: |
| الاعتمادات المستندية                                                          |12,511 | 9,583 |10,674 |
| حوالات                                                                   |   335 |   138 |   192 |
| الأغراض الشخصية                                                             | 8,159 | 6,468 | 8,022 |
| بطاقات صغار التجار                                                          |     3 |     0 |     0 |
| **المجموع الفرعي: استخدامات المصارف التجارية**                              |**21,008**|**16,189**|**18,888**|

**ملخص المجاميع والوضع المالي (مليار دولار أمريكي)**

| البند                                                              | 2023 | 2022 | 2021 |
| :----------------------------------------------------------------- | ---: | ---: | ---: |
|إجمالي استخدامات والتزامات الدولة                                      | 14.3| 12.3|  9.2 |
|   إجمالي استخدامات المصارف التجارية                                      |21,0|16.1| 18.8|
| **إجمالي الاستخدامات والالتزامات**                                     |**35.3**|**28.5**|**28.1**|
| إيرادات النقد الأجنبي                                                  | 25.4 | 27.3 | 22.9 |
| **الفرق بين الإيرادات والاستخدامات والالتزامات**                       |**-9.9**|**-1.2**|**-5.2**|


# كشف بالمبالغ المشتراه للمصارف التجارية
## خلال الفترة من 2023/01/01 إلى 2023/12/31

| إجمالي المبالغ المباعة بالدولار الأمريكي | الأغراض الشخصية | بطاقات التجار | الحوالات | الاعتمادات | اسم المصرف                         |
| -----------------------------------: | ---------------: | ------------: | --------: | ---------: | :------------------------------------ |
|                        1,447,552,124.23 |     358,189,705.00 |          0.00 |50,926,103.88|1,038,436,315.35| المصرف الاسلامي الليبي             |
|                         225,675,168.33 |               0.00 |          0.00 |          0.00|   225,675,168.33| مصرف التضامن                       |
|                        2,916,536,247.27 |   1,380,729,460.00 |   2,200,000.00 | 5,467,409.55| 1,528,139,377.72| المصرف التجاري الوطني                 |
|                          91,179,028.31 |       877,680.00 |          0.00 |28,422,017.80|    61,879,330.51| المصرف الليبي الخارجي                 |
|                        1,493,331,472.71 |     972,346,231.00 |          0.00 | 3,377,257.53|   517,607,984.18| المصرف المتحد للتجارة والاستثمار    |
|                                    0.00 |               0.00 |          0.00 |          0.00|             0.00| مصرف الاجماع العربي                 |
|                        2,102,187,761.83 |   1,401,625,527.00 |      800,000.00| 5,595,689.59|   694,166,545.24| مصرف الأمان للتجارة والاستثمار      |
|                          409,200,382.01 |     401,522,966.00 |          0.00 | 1,977,416.01|      5,700,000.00| مصرف التجارة والتنمية                 |
|                        2,474,861,396.12 |   1,011,635,000.00 |         0.00|54,253,179.02|  1,408,973,217.10 | مصرف الجمهورية                      |
|                          625,512,857.66 |       1,273,490.00 |          0.00 |31,563,268.61|   592,676,099.05| مصرف الخليج الأول الليبي          |
|                          448,530,942.62 |      11,860,424.00 |          0.00 |31,812,118.56|   404,858,400.06| مصرف السرايا                        |
|                        1,075,420,608.18 |     629,063,496.00 |           0.00| 12,465,346.52    |433,891,765.66| مصرف الصحارى                        |
|                           60,543,786.35 |       9,520,356.82 |           0.00|          0.00| 51,023,429.53  | مصرف المتوسط                        |
|                        1,931,594,984.97 |     346,203,445.20 |         0.00|38,779,785.48|  1,546,611,754.29    | مصرف النوران                        |
|                          252,070,056.06 |     104,785,327.00 |           0.00| 1,882,931.89|  145,401,797.17    |  مصرف الواحة                         |
|                        2,393,449,360.35 |     376,494,027.00 |          0.00 |   943,419.35| 2,016,011,914.00| مصرف الوحدة                         |
|                          230,763,993.61 |       4,317,795.00 |          0.00 |          0.00|   226,446,198.61| مصرف الوفاء                         |
|                          718,732,746.58 |     296,421,952.00 |          0.00 |45,455,212.20|   376,855,582.38| مصرف شمال أفريقيا                   |
|                        1,632,794,918.37 |     805,725,045.00 |      100,000.00 |14,105,285.87|   812,864,587.50| مصرف اليقين                          |
|                          478,769,341.20 |      45,931,812.00 |         0.00| 8,663,873.65|  424,173,655.55 | مصرف الأندلس                        |
|**21,008,707,176.76**|**8,158,523,739.02**|**3,100,000.00**|**335,690,315.51**|**12,511,393,122.23**| **الإجمالي**                        |


## إنّ مصرف ليبيا المركزي إذ ينشر هذه البيانات يؤكد على ما يلي:

1. يأتي هذا البيان في إطار استراتيجية مصرف ليبيا المركزي لتحقيق أعلى معدلات الإفصاح والشفافية استجابةً للمطالب المحلية والدولية، ويواصل المصرف جهودَه في تطوير الإفصاح والشفافية بالتعاون والتنسيق مع بقية مؤسسات الدولة.

2. تضمن البيان مقارنة بين الأعوام: 2021 – 2022 – 2023، للوقوف على هيكل الإنفاق العام:
   - بلغ إجمالي المرتبات 65 مليار دينار (منها 4 مليار دينار مرتبات للمؤسسة الوطنية للنفط، ومليار دينار مرتبات لصالح جهات أخرى) خلال عام 2023.
   - حسب تقديرات ديوان المحاسبة للعام 2022 بلغ بند دعم المحروقات 83 مليار دينار (أي ما يعادل 17.2 مليار دولار)، 50% منها تقريباً وجهت لتوريد الوقود، وتمت عبر المبادلة خارج أبواب الميزانية.
   - دعم المحروقات يتطلب تكاتف جهود مؤسسات الدولة لمعالجته.
   - بلغ استخدام المصارف للنقد الأجنبي خلال العام 2023 مبلغ 21 مليار دولار، بزيادة قدرها 5 مليار دولار عن عام 2022.
   - بلغ إجمالي ما تم إحالته إلى مراقبات الخدمات المالية بالمدن الليبية 25 مليار دينار يمثّل 42% من إجمالي الباب الأول.

3. يصدر مع هذا البيان ملحق خاص يتضمن تفاصيل استخدامات المصارف التجارية للنقد الأجنبي حسب السلع، والدول، والشركات، والمنافذ الموردة عن طريقها تلك السلع (للاطلاع على التفاصيل اضغط هنا) هذا فضلاً عن البيان الأسبوعي الذي ينشره مصرف ليبيا المركزي حول الاعتمادات المستندية المنفذة خلال الأسبوع.

4. بلغت الإيرادات النفطية الموردة إلى مصرف ليبيا المركزي خلال الفترة 25.4 مليار دولار، بينما بلغ إجمالي الاستخدامات والالتزامات القائمة حتى نهاية ديسمبر 2023 مبلغ 35.3 مليار دولار.

5. لاحظ مصرف ليبيا المركزي استنـــــزافاً في استخدامات النقد الأجنبي خلال الفترة بارتفاع قدره 5 مليار دولار عن العام 2022.

6. تدني إيرادات الجمارك الموردة إلى المصرف المركزي نسبةً إلى استخدامات المصارف من النقد الأجنبي، حيث بلغت النسبة 0.3% فقط.

7. بند "حوالات لصالح جهات أخرى" الوارد في جدول استخدامات النقد الأجنبي بقيمة 917 مليون دولار يمثّل مصروفات لصالح جهات عامة: (جهاز خدمات الإسعاف الطائر - الجهاز التنفيذي للطيران الخاص - أجهزة رقابية - مركز طب الميدان - مساهمات وزارة الخارجية).

8. بند "اعتمادات لصالح جهات أخرى" بقيمة 280 مليون دولار الوارد في جدول استخدامات النقد الأجنبي يشمل كلا من : (وزارة الصحة - وزارة المواصلات - جهاز تنفيذ مشروعات المواصلات - جهاز تنمية وتطوير المراكز الإدارية - الجهاز التنفيذي للطيران الخاص - الإدارة العامة للجوازات والجنسية - مصلحة الطيران المدني - وزارة الداخلية - مشروع النهر الصناعي - جهاز الاسعاف الطائر).

9. تم تعلية مبلغ 10 مليار دينار من الباب الثالث حتى تتم المراجعة.

10. تخصم فاتورة المحروقات من مبيعات النفط من قبل المؤسسة الوطنية للنفط مباشرة منذ نوفمبر 2021.

11. في إطار تنفيذ استراتيجية مصرف ليبيا المركزي لتوفير السيولة النقدية، تم خلال الفترة توزيع مبلغ 106 مليار دينار لفروع المصارف التجارية بكافة المدن الليبية.

12. بلغ إجمالي عدد الصكوك المقبولة خلال الفترة عبر نظام المقاصة الالكترونية 2,372,821 صكاً بقيمة إجمالية حوالي 71.9 مليار دينار نُفّذت عبر 648 فرعاً مصرفياً ومركز مقاصة على كامل التراب الليبي.

13. بلغ عدد إجمالي البطاقات المفعلة 3,611,392 بطاقة وبلغ عدد أجهزة نقاط البيع العاملة 48,958 جهازاً وبلغ عدد العمليات على البطاقات 49,125,179 عملية، وبلغ إجمالي حجم التداول 9.6 مليار دينار.

14. بلغ عدد المحافظ الإلكترونية 139,937 محفظة وبلغ عدد نقاط القبول للمحافظ الإلكترونية 2,498 نقطة قبول وبلغ عدد العمليات على المحافظ 478,034 عملية، وبلغ إجمالي حجم التداول 36 مليون دينار.

15. للحصول على تفاصيل القطاعات وبيانات الجهات، انقر على الرابط المدمج في اسم القطاع.

16. تسهيلاً على الباحثين والمحللين الراغبين في استخدام المعلومات والأرقام الواردة في البيان، تم إرفاق ملف بصيغة (Excel) على الموقع الرسمي للمصرف.

17. ينبّه مصرف ليبيا المركزي إلى أنّ الاستمرار بنفس الوتيرة للإنفاق العام، وتفاقم العجز في إيرادات النقد الأجنبي لتغطية الطلب المتزايد، ستكون له آثار سلبية على الوضع الاقتصادي، وعلى احتياطيات المصرف المركزي، وعلى الاستدامة المالية للدولة، ويزيد من الضغوط على سعر الصرف.

# بيان مصرف ليبيا المركزي - الإيرادات والنفقات (1 يناير - 31 ديسمبر 2023) - مُنسق للبحث الدلالي والتجزئة


**الأقسام (والأقسام الفرعية):**

##   **1. الإيرادات (2023):**  (مقارنة مع 2021 و 2022)
    *   `1.1 إجمالي الإيرادات: 125.9 مليار دينار ليبي` (2021: 105.7 مليار، 2022: 134.4 مليار)
    *   `1.2 إيرادات مبيعات النفط: 99.1 مليار دينار ليبي` (2021: 103.4 مليار، 2022: 105.5 مليار)
    *   `1.3 إيرادات إتاوات نفطية: 12.3 مليار دينار ليبي` (2021: 0، 2022: 13.6 مليار)
    *   `1.4 إيرادات إتاوات نفطية عن سنوات سابقة: 10.3 مليار دينار ليبي` (2021: 0، 2022: 11.4 مليار)
    *   `1.5 إيرادات الضرائب: 2.4 مليار دينار ليبي` (2021: 799 مليون، 2022: 1.4 مليار)
    *   `1.6 إيرادات الجمارك: 333 مليون دينار ليبي` (2021: 311 مليون، 2022: 211 مليون)
        *   `1.6.1 ملاحظة: تدني إيرادات الجمارك مقارنة باستخدامات النقد الأجنبي للمصارف (0.3%).`
    *   `1.7 إيرادات الاتصالات: 506 مليون دينار ليبي` (2021: 198 مليون، 2022: 529 مليون)
    *   `1.8 إيرادات مبيعات الوقود المحلية: 180 مليون دينار ليبي` (2021: 450 مليون، 2022: 265 مليون)
    *   `1.9 إيرادات أخرى: 792 مليون دينار ليبي` (2021: 494 مليون، 2022: 1.5 مليار)
        *   `1.9.1 مصادر الإيرادات الأخرى: استردادات، رسوم جوازات، رسوم ملكية سيارات، غرامات، رسوم أخرى.`
        *   `1.9.2 مصدر الإيرادات الأخرى: مراقبات الخدمات المالية بالمدن الليبية، نظير خدمات عامة.`
     * `1.10 إيرادات النقد الأجنبي (الواردة إلى مصرف ليبيا المركزي): 25.4 مليار دولار`

##   **2. النفقات (2023):** (مقارنة مع 2021 و 2022)
    *   `2.1 إجمالي الإنفاق العام: 125.7 مليار دينار ليبي` (2021: 85.8 مليار، 2022: 127.9 مليار)
    *   `2.2 الباب الأول (المرتبات): 60 مليار دينار ليبي` (2021: 33.1 مليار، 2022: 47.1 مليار)
        *   `2.2.1  ملاحظة: 4 مليار دينار مرتبات للمؤسسة الوطنية للنفط (ضمن الـ 60 مليار).`
        *   `2.2.2 ملاحظة: مليار دينار مرتبات لجهات أخرى (ضمن الـ 60 مليار).`
        *  `2.2.3  إجمالي المبالغ المحالة إلى مراقبات الخدمات المالية بالمدن: 25 مليار دينار (42% من إجمالي الباب الأول).`
    *   `2.3 الباب الثاني (النفقات التشغيلية): 9 مليار دينار ليبي` (2021: 8 مليار، 2022: 9 مليار)
    *   `2.4 الباب الثالث (التنمية): 12 مليار دينار ليبي` (2021: 17.4 مليار، 2022: 17.5 مليار)
       *    `2.4.1  ملاحظة: تم تعلية مبلغ 10 مليار من الباب الثالث حتى تتم المراجعة.`
    *   `2.5 الباب الرابع (الدعم): 20 مليار دينار ليبي` (2021: 20.8 مليار، 2022: 20 مليار)
        *    `2.5.1 ملاحظة: لا يشمل دعم المحروقات في 2022-2023 (تخصم قيمته عن طريق المبادلة من قبل المؤسسة الوطنية للنفط).`
        *   `2.5.2 ملاحظة (حسب تقديرات ديوان المحاسبة لعام 2022): بلغ دعم المحروقات 83 مليار دينار (17.2 مليار دولار)، 50% منها لتوريد الوقود.`
    *   `2.6 الباب الخامس (الطوارئ): 0 دينار ليبي` (2021: 6.5 مليار، 2022: 0)
    *   `2.7 إجمالي الإنفاق على الأبواب (1-5): 101 مليار دينار ليبي` (2021: 85.8 مليار، 2022: 93.6 مليار)
    *   `2.8 الميزانية الاستثنائية للمؤسسة الوطنية للنفط: 17.5 مليار دينار ليبي` (2021: 0، 2022: 34.3 مليار)
    *   `2.9 الميزانية الاستثنائية للشركة العامة للكهرباء: 7.2 مليار دينار ليبي` (2021: 0، 2022: 0)
    *   `2.10 تفصيل الإنفاق حسب القطاعات والجهات:`
        *   ...(قائمة تفصيلية لكل قطاع وجهة تابعة، بنفس التنسيق الموضح سابقًا، مع تضمين إجمالي الإنفاق لكل جهة وتفصيله حسب الأبواب)...
         * `2.10.1  القطاعات والجهات: مجلس النواب والجهات التابعة له , إجمالي الإنفاق: 1,671,141,422.304`
         *    `2.10.1.1  الباب الأول: 1,044,980,262.304`
         *   `2.10.1.2 الباب الثاني: 360,934,072.000`
          *  `2.10.1.3  الباب الثالث: 265,227,088.000`
          *  `2.10.1.4 الباب الرابع: 00.000`
        *   `2.10.N الإجمالي: 125,726,362,884.528`
     *  `2.11  تفصيل مبالغ الباب الأول المحولة لمراقبات الخدمات المالية`
         *   `2.11.1 الجهة: مراقبة الخدمات المالية - اجخرة، المبلغ: 13463968.503`
             ...(قائمة تفصيلية لكل مدينة/مكتب خدمات مالية والمبلغ المحول)
         *  `2.11.N  الإجمالي: 24,924,094,547.714`

## *   **3. استخدامات النقد الأجنبي (2023) (بملايين الدولارات الأمريكية):** (مقارنة مع 2021 و 2022)

    *   `3.1 إجمالي استخدامات والتزامات النقد الأجنبي: 35.3 مليار دولار` (2021: 28.1 مليار، 2022: 28.5 مليار)
    *    `3.1.1  ملاحظة: ارتفاع في استخدامات النقد الأجنبي بمقدار 5 مليارات دولار عن عام 2022`
     *  `3.1.2  الفرق بين إيرادات واستخدامات/التزامات النقد الأجنبي: -9.9 مليار دولار.`
    *   `3.2 استخدامات والتزامات الدولة (عن طريق مصرف ليبيا المركزي): 14.332 مليار دولار` (2021: 9.225 مليار، 2022: 12.343 مليار)
        *   `3.2.1 مرتبات العاملين بالخارج: 339 مليون دولار` (2021: 155 مليون، 2022: 247 مليون)
        *   `3.2.2 منح الطلبة الدارسين بالخارج: 102 مليون دولار` (2021: 157 مليون، 2022: 142 مليون)
        *   `3.2.3 العلاج بالخارج: 108 مليون دولار` (2021: 52 مليون، 2022: 163 مليون)
        *   `3.2.4 دعم المحروقات: 0 دولار` (تمت المبادلة)
        *   `3.2.5 المؤسسة الوطنية للنفط: 2,548 مليون دولار` (2021: 803 مليون، 2022: 2,365 مليون)
        *   `3.2.6 حوالات لصالح جهات أخرى: 917 مليون دولار` (2021: 948 مليون، 2022: 512 مليون)
            *   `3.2.6.1 تفصيل الجهات: جهاز خدمات الإسعاف الطائر، الجهاز التنفيذي للطيران الخاص، أجهزة رقابية، مركز طب الميدان، مساهمات وزارة الخارجية.`
        *   `3.2.7 جهاز الإمداد الطبي: 377 مليون دولار` (2021: 331 مليون، 2022: 269 مليون)
        *   `3.2.8 الشركة العامة للكهرباء: 741 مليون دولار` (2021: 663 مليون، 2022: 465 مليون)
        *   `3.2.9 التعليم والتعليم العالي: 26 مليون دولار` (2021: 57 مليون، 2022: 88 مليون)
        *   `3.2.10 اعتمادات لصالح جهات أخرى: 280 مليون دولار` (2021: 249 مليون، 2022: 166 مليون)
            *   `3.2.10.1 تفصيل الجهات: وزارة الصحة، وزارة المواصلات، جهاز تنفيذ مشروعات المواصلات، جهاز تنمية وتطوير المراكز الإدارية، الجهاز التنفيذي للطيران الخاص، الإدارة العامة للجوازات والجنسية، مصلحة الطيران المدني، وزارة الداخلية، مشروع النهر الصناعي، جهاز الإسعاف الطائر.`
        *    `3.2.11 التزامات قائمة على جهات عامة: 8,894 مليون دولار`
    *   `3.3 استخدامات المصارف التجارية: 21.008 مليار دولار` (2021: 18.888 مليار، 2022: 16.189 مليار)
        *   `3.3.1 الاعتمادات المستندية: 12.511 مليار دولار` (2021: 10.674 مليار، 2022: 9.583 مليار)
        *   `3.3.2 الحوالات: 335 مليون دولار` (2021: 192 مليون، 2022: 138 مليون)
        *   `3.3.3 الأغراض الشخصية: 8.159 مليار دولار` (2021: 8.022 مليار، 2022: 6.468 مليار)
        *   `3.3.4 بطاقات صغار التجار: 3 مليون دولار` (2021: 0، 2022: 0)
         *   `3.3.5 تفصيل المبالغ المشتراه لكل مصرف:`
              *   `3.3.5.1  المصرف الإسلامي الليبي: 1,447,552,124.23`
                *    `3.3.5.1.1  الاعتمادات:  1,038,436,315.35`
                *    `3.3.5.1.2  الحوالات: 50,926,103.88`
                *   `3.3.5.1.3 بطاقات التجار: 0.00`
                *   `3.3.5.1.4  الأغراض الشخصية: 358,189,705.00`

                ... (تفصيل كامل لكل مصرف وبند)
             *  `3.3.5.N الإجمالي: 21,008,707,176.76`

## *   **4. ملاحظات مصرف ليبيا المركزي:**
    *   `4.1 استراتيجية الشفافية والإفصاح: التزام المصرف بأعلى معدلات الإفصاح استجابة للمطالب المحلية والدولية.`
    *  `4.2 مقارنة بين الأعوام (2021-2023): للوقوف على هيكل الإنفاق العام.`
    *   `4.3 ملحق تفصيلي: وجود ملحق بتفاصيل استخدامات المصارف التجارية للنقد الأجنبي (سلع، دول، شركات، منافذ).`
    *   `4.4  توزيع سيولة نقدية: تم توزيع 106 مليار دينار`
    *   `4.5 نظام المقاصة الإلكترونية: 2,372,821 صكاً بقيمة 71.9 مليار دينار عبر 648 فرعًا مصرفيًا.`
    *   `4.6 البطاقات المصرفية: 3,611,392 بطاقة مفعلة.`
    *   `4.7 أجهزة نقاط البيع: 48,958 جهازًا عاملًا.`
    *   `4.8 معاملات البطاقات: 49,125,179 عملية بقيمة 9.6 مليار دينار.`
    *   `4.9 المحافظ الإلكترونية: 139,937 محفظة.`
    *  `4.10  نقاط القبول: 2,498 نقطة`
    * `4.11   عدد العمليات: 478,034`
    *  `4.12  حجم التداول: 36 مليون`
    *   `4.13 تفاصيل القطاعات والجهات: روابط مضمنة في البيان للوصول إلى التفاصيل.`
    *   `4.14 ملف Excel: متاح على الموقع الرسمي للمصرف لتسهيل استخدام البيانات.`
    *   `4.15 تحذير من استمرار الإنفاق وتفاقم العجز: آثار سلبية على الوضع الاقتصادي، احتياطيات المصرف، الاستدامة المالية، وسعر الصرف.`
     * `4.16  عدم الإفصاح عن أرباح مصرف ليبيا المركزي: بسبب عدم اعتماد الإدارة السابقة آلية شفافة للإفصاح. جاري العمل على التحقق والإفصاح`
